### ISSUE TITLE
automatically reloading upon file changes

### ISSUE THREAD

**Issue by rahji** [antsankov/go-live#3]
The FAQ presents this as a replacement for the npm live-server, but a main feature of that other software is that it reloads when the files are updated. I don't _think_ this application does that but I wanted to verify that I'm not missing something.

**Comment by antsankov** [comment]
go-live will automatically serve any file changes in the directory it is serving. You need to reload the browser to pick up these changes, it does not reload your browser anytime there is a change (which I believe live-server does)
